// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectMedicationDosageLastChanged1 = require('../../../src/Extensions/ExtensionCareConnectMedicationDosageLastChanged1.js')

describe('Care Connect Extension ExtensionCareConnectMedicationDosageLastChanged1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectMedicationDosageLastChanged1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectMedicationDosageLastChanged1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-MedicationDosageLastChanged-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Datetime', function () {
      let ext = new ExtensionCareConnectMedicationDosageLastChanged1()
      ext.datetime = 'some string'
      let dt = ext.datetime
      expect(dt).toBe('some string')
    })
  })
})
