// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectRegistrationDetails1 = require('../../../src/Extensions/ExtensionCareConnectRegistrationDetails1.js')

describe('Care Connect Extension ExtensionCareConnectRegistrationDetails1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectRegistrationDetails1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectRegistrationDetails1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-RegistrationDetails-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set registrationPeriod', function () {
      let ext = new ExtensionCareConnectRegistrationDetails1()
      // period
      ext.registrationPeriod = 'foobar'
    })
    it('Get/Set registrationType', function () {
      let ext = new ExtensionCareConnectRegistrationDetails1()
      // codeableconcept
      ext.registrationType = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
      let value = ext.registrationType
      expect(value.code).toBe('somecode')
      expect(value.display).toBe('some display')
    })
    it('Get/Set preferredBranchSurgery', function () {
      let ext = new ExtensionCareConnectRegistrationDetails1()
      // reference
      ext.preferredBranchSurgery = { 'display': 'some display', 'reference': 'someref' }
      let value = ext.preferredBranchSurgery
      expect(value.reference).toBe('someref')
      expect(value.display).toBe('some display')
    })
  })
})
