// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectReasonCondition1 = require('../../../src/Extensions/ExtensionCareConnectReasonCondition1.js')

describe('Care Connect Extension ExtensionCareConnectReasonCondition1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectReasonCondition1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectReasonCondition1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ReasonCondition-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Reference', function () {
      let ext = new ExtensionCareConnectReasonCondition1()
      ext.reference = { 'reference': 'some reference' }
      let rf = ext.reference
      expect(rf.reference).toBe('some reference')
    })
    it('Get/Set Codeableconcept', function () {
      let ext = new ExtensionCareConnectReasonCondition1()
      if (!ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = ''
        let cc = ext.codeableConcept
        expect(cc.code).toBe('')
        expect(cc.display).toBe('')
      } else if (ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = { 'code': '', 'display': 'some display' , 'system': 'http://snomed.info/sct' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('')
        expect(cc.display).toBe('some display')
      } else { // Has no valueset
        ext.codeableConcept = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('somecode')
        expect(cc.display).toBe('some display')
      }
    })
  })
})
