// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectMedicationRepeatInformation1 = require('../../../src/Extensions/ExtensionCareConnectMedicationRepeatInformation1.js')

describe('Care Connect Extension ExtensionCareConnectMedicationRepeatInformation1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectMedicationRepeatInformation1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectMedicationRepeatInformation1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-MedicationRepeatInformation-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set numberOfRepeatPrescriptionsAllowed', function () {
      let ext = new ExtensionCareConnectMedicationRepeatInformation1()
      // unsignedint
      ext.numberOfRepeatPrescriptionsAllowed = 'foobar'
    })
    it('Get/Set numberOfRepeatPrescriptionsIssued', function () {
      let ext = new ExtensionCareConnectMedicationRepeatInformation1()
      // unsignedint
      ext.numberOfRepeatPrescriptionsIssued = 'foobar'
    })
    it('Get/Set authorisationExpiryDate', function () {
      let ext = new ExtensionCareConnectMedicationRepeatInformation1()
      // datetime
      ext.authorisationExpiryDate = 'foobar'
    })
  })
})
