// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectProbabilityOfRecurrence1 = require('../../../src/Extensions/ExtensionCareConnectProbabilityOfRecurrence1.js')

describe('Care Connect Extension ExtensionCareConnectProbabilityOfRecurrence1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectProbabilityOfRecurrence1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectProbabilityOfRecurrence1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ProbabilityOfRecurrence-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set String', function () {
      let ext = new ExtensionCareConnectProbabilityOfRecurrence1()
      ext.string = 'some string'
      let s = ext.string
      expect(s).toBe('some string')
    })
  })
})
