// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectMedicationPrescribingAgency1 = require('../../../src/Extensions/ExtensionCareConnectMedicationPrescribingAgency1.js')

describe('Care Connect Extension ExtensionCareConnectMedicationPrescribingAgency1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectMedicationPrescribingAgency1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectMedicationPrescribingAgency1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-MedicationPrescribingAgency-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Codeableconcept', function () {
      let ext = new ExtensionCareConnectMedicationPrescribingAgency1()
      if (!ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = 'prescribed-at-gp-practice'
        let cc = ext.codeableConcept
        expect(cc.code).toBe('prescribed-at-gp-practice')
        expect(cc.display).toBe('Prescribed at GP practice')
      } else if (ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = { 'code': 'prescribed-at-gp-practice', 'display': 'some display' , 'system': 'http://snomed.info/sct' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('prescribed-at-gp-practice')
        expect(cc.display).toBe('some display')
      } else { // Has no valueset
        ext.codeableConcept = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('somecode')
        expect(cc.display).toBe('some display')
      }
    })
  })
})
