// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectListWarningCode1 = require('../../../src/Extensions/ExtensionCareConnectListWarningCode1.js')

describe('Care Connect Extension ExtensionCareConnectListWarningCode1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectListWarningCode1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectListWarningCode1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ListWarningCode-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Code', function () {
      let ext = new ExtensionCareConnectListWarningCode1()
      ext.code = 'foo'
      let cd = ext.code
      expect(cd).toBe('foo')
    })
  })
})
