// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectValueApproximation1 = require('../../../src/Extensions/ExtensionCareConnectValueApproximation1.js')

describe('Care Connect Extension ExtensionCareConnectValueApproximation1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectValueApproximation1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectValueApproximation1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ValueApproximation-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Boolean', function () {
      let ext = new ExtensionCareConnectValueApproximation1()
      ext.boolean = true
      let bl = ext.boolean
      expect(bl).toBe(true)
    })
  })
})
