// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectConditionRelationship1 = require('../../../src/Extensions/ExtensionCareConnectConditionRelationship1.js')

describe('Care Connect Extension ExtensionCareConnectConditionRelationship1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectConditionRelationship1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectConditionRelationship1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ConditionRelationship-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set typevalueCode', function () {
      let ext = new ExtensionCareConnectConditionRelationship1()
      ext.typevalueCode = 'foobar'
      let value = ext.typevalueCode
      expect(value).toBe('foobar')
    })
    it('Get/Set targetvalueReference', function () {
      let ext = new ExtensionCareConnectConditionRelationship1()
      ext.targetvalueReference = { 'display': 'some display', 'reference': 'someref' }
      let value = ext.targetvalueReference
      expect(value.reference).toBe('someref')
      expect(value.display).toBe('some display')
    })
  })
})
