// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectMedicationQuantityText1 = require('../../../src/Extensions/ExtensionCareConnectMedicationQuantityText1.js')

describe('Care Connect Extension ExtensionCareConnectMedicationQuantityText1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectMedicationQuantityText1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectMedicationQuantityText1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-MedicationQuantityText-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set String', function () {
      let ext = new ExtensionCareConnectMedicationQuantityText1()
      ext.string = 'some string'
      let s = ext.string
      expect(s).toBe('some string')
    })
  })
})
