// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectMedicationChangeSummary1 = require('../../../src/Extensions/ExtensionCareConnectMedicationChangeSummary1.js')

describe('Care Connect Extension ExtensionCareConnectMedicationChangeSummary1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectMedicationChangeSummary1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectMedicationChangeSummary1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-MedicationChangeSummary-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set status', function () {
      let ext = new ExtensionCareConnectMedicationChangeSummary1()
      // code
      ext.status = 'foobar'
    })
    it('Get/Set indicationForChange', function () {
      let ext = new ExtensionCareConnectMedicationChangeSummary1()
      // codeableconcept
      ext.indicationForChange = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
      let value = ext.indicationForChange
      expect(value.code).toBe('somecode')
      expect(value.display).toBe('some display')
    })
    it('Get/Set dateChanged', function () {
      let ext = new ExtensionCareConnectMedicationChangeSummary1()
      // datetime
      ext.dateChanged = 'foobar'
    })
    it('Get/Set detailsOfAmendment', function () {
      let ext = new ExtensionCareConnectMedicationChangeSummary1()
      // string
      ext.detailsOfAmendment = 'foobar'
    })
  })
})
