// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectOutcomeOfAttendance1 = require('../../../src/Extensions/ExtensionCareConnectOutcomeOfAttendance1.js')

describe('Care Connect Extension ExtensionCareConnectOutcomeOfAttendance1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectOutcomeOfAttendance1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectOutcomeOfAttendance1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-OutcomeOfAttendance-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Codeableconcept', function () {
      let ext = new ExtensionCareConnectOutcomeOfAttendance1()
      if (!ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = '1'
        let cc = ext.codeableConcept
        expect(cc.code).toBe('1')
        expect(cc.display).toBe('Discharged from Consultant\'s care (last attendance)')
      } else if (ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = { 'code': '1', 'display': 'some display' , 'system': 'http://snomed.info/sct' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('1')
        expect(cc.display).toBe('some display')
      } else { // Has no valueset
        ext.codeableConcept = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('somecode')
        expect(cc.display).toBe('some display')
      }
    })
  })
})
