// This code was autogenerated from BuildExtensions.py

const Extensioncodingsctdescid = require('../../../src/Extensions/Extensioncodingsctdescid.js')

describe('Care Connect Extension Extensioncodingsctdescid', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new Extensioncodingsctdescid()
      expect(ext).toBeInstanceOf(Extensioncodingsctdescid)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-coding-sctdescid')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set descriptionId', function () {
      let ext = new Extensioncodingsctdescid()
      // id
      ext.descriptionId = 'foobar'
    })
    it('Get/Set descriptionDisplay', function () {
      let ext = new Extensioncodingsctdescid()
      // string
      ext.descriptionDisplay = 'foobar'
    })
  })
})
