// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectEthnicCategory1 = require('../../../src/Extensions/ExtensionCareConnectEthnicCategory1.js')

describe('Care Connect Extension ExtensionCareConnectEthnicCategory1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectEthnicCategory1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectEthnicCategory1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-EthnicCategory-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Codeableconcept', function () {
      let ext = new ExtensionCareConnectEthnicCategory1()
      if (!ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = 'A'
        let cc = ext.codeableConcept
        expect(cc.code).toBe('A')
        expect(cc.display).toBe('British, Mixed British')
      } else if (ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = { 'code': 'A', 'display': 'some display' , 'system': 'http://snomed.info/sct' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('A')
        expect(cc.display).toBe('some display')
      } else { // Has no valueset
        ext.codeableConcept = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('somecode')
        expect(cc.display).toBe('some display')
      }
    })
  })
})
