// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectNHSCommunication1 = require('../../../src/Extensions/ExtensionCareConnectNHSCommunication1.js')

describe('Care Connect Extension ExtensionCareConnectNHSCommunication1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectNHSCommunication1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectNHSCommunication1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-NHSCommunication-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set language', function () {
      let ext = new ExtensionCareConnectNHSCommunication1()
      // codeableconcept
      ext.language = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
      let value = ext.language
      expect(value.code).toBe('somecode')
      expect(value.display).toBe('some display')
    })
    it('Get/Set preferred', function () {
      let ext = new ExtensionCareConnectNHSCommunication1()
      // boolean
      ext.preferred = 'foobar'
    })
    it('Get/Set modeOfCommunication', function () {
      let ext = new ExtensionCareConnectNHSCommunication1()
      // codeableconcept
      ext.modeOfCommunication = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
      let value = ext.modeOfCommunication
      expect(value.code).toBe('somecode')
      expect(value.display).toBe('some display')
    })
    it('Get/Set communicationProficiency', function () {
      let ext = new ExtensionCareConnectNHSCommunication1()
      // codeableconcept
      ext.communicationProficiency = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
      let value = ext.communicationProficiency
      expect(value.code).toBe('somecode')
      expect(value.display).toBe('some display')
    })
    it('Get/Set interpreterRequired', function () {
      let ext = new ExtensionCareConnectNHSCommunication1()
      // boolean
      ext.interpreterRequired = 'foobar'
    })
  })
})
