// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectResidentialStatus1 = require('../../../src/Extensions/ExtensionCareConnectResidentialStatus1.js')

describe('Care Connect Extension ExtensionCareConnectResidentialStatus1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectResidentialStatus1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectResidentialStatus1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ResidentialStatus-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Codeableconcept', function () {
      let ext = new ExtensionCareConnectResidentialStatus1()
      if (!ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = 'H'
        let cc = ext.codeableConcept
        expect(cc.code).toBe('H')
        expect(cc.display).toBe('UK Resident')
      } else if (ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = { 'code': 'H', 'display': 'some display' , 'system': 'http://snomed.info/sct' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('H')
        expect(cc.display).toBe('some display')
      } else { // Has no valueset
        ext.codeableConcept = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('somecode')
        expect(cc.display).toBe('some display')
      }
    })
  })
})
