// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectParentPresent1 = require('../../../src/Extensions/ExtensionCareConnectParentPresent1.js')

describe('Care Connect Extension ExtensionCareConnectParentPresent1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectParentPresent1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectParentPresent1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ParentPresent-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Boolean', function () {
      let ext = new ExtensionCareConnectParentPresent1()
      ext.boolean = true
      let bl = ext.boolean
      expect(bl).toBe(true)
    })
  })
})
