// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectMedicationStatementLastIssueDate1 = require('../../../src/Extensions/ExtensionCareConnectMedicationStatementLastIssueDate1.js')

describe('Care Connect Extension ExtensionCareConnectMedicationStatementLastIssueDate1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectMedicationStatementLastIssueDate1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectMedicationStatementLastIssueDate1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-MedicationStatementLastIssueDate-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Datetime', function () {
      let ext = new ExtensionCareConnectMedicationStatementLastIssueDate1()
      ext.datetime = 'some string'
      let dt = ext.datetime
      expect(dt).toBe('some string')
    })
  })
})
