// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectEncounterTransport1 = require('../../../src/Extensions/ExtensionCareConnectEncounterTransport1.js')

describe('Care Connect Extension ExtensionCareConnectEncounterTransport1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectEncounterTransport1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectEncounterTransport1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-EncounterTransport-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set transportType', function () {
      let ext = new ExtensionCareConnectEncounterTransport1()
      // codeableconcept
      ext.transportType = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
      let value = ext.transportType
      expect(value.code).toBe('somecode')
      expect(value.display).toBe('some display')
    })
    it('Get/Set transportPeriod', function () {
      let ext = new ExtensionCareConnectEncounterTransport1()
      // period
      ext.transportPeriod = 'foobar'
    })
    it('Get/Set reasonForTransport', function () {
      let ext = new ExtensionCareConnectEncounterTransport1()
      // string
      ext.reasonForTransport = 'foobar'
    })
  })
})
