// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectPrescriptionType1 = require('../../../src/Extensions/ExtensionCareConnectPrescriptionType1.js')

describe('Care Connect Extension ExtensionCareConnectPrescriptionType1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectPrescriptionType1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectPrescriptionType1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-PrescriptionType-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Codeableconcept', function () {
      let ext = new ExtensionCareConnectPrescriptionType1()
      if (!ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = 'acute'
        let cc = ext.codeableConcept
        expect(cc.code).toBe('acute')
        expect(cc.display).toBe('Acute')
      } else if (ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = { 'code': 'acute', 'display': 'some display' , 'system': 'http://snomed.info/sct' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('acute')
        expect(cc.display).toBe('some display')
      } else { // Has no valueset
        ext.codeableConcept = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('somecode')
        expect(cc.display).toBe('some display')
      }
    })
  })
})
