// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectDeliveryChannel1 = require('../../../src/Extensions/ExtensionCareConnectDeliveryChannel1.js')

describe('Care Connect Extension ExtensionCareConnectDeliveryChannel1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectDeliveryChannel1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectDeliveryChannel1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-DeliveryChannel-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Code', function () {
      let ext = new ExtensionCareConnectDeliveryChannel1()
      ext.code = 'foo'
      let cd = ext.code
      expect(cd).toBe('foo')
    })
  })
})
