// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectReferralRequestMethod1 = require('../../../src/Extensions/ExtensionCareConnectReferralRequestMethod1.js')

describe('Care Connect Extension ExtensionCareConnectReferralRequestMethod1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectReferralRequestMethod1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectReferralRequestMethod1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ReferralRequestMethod-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Codeableconcept', function () {
      let ext = new ExtensionCareConnectReferralRequestMethod1()
      if (!ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = ''
        let cc = ext.codeableConcept
        expect(cc.code).toBe('')
        expect(cc.display).toBe('')
      } else if (ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = { 'code': '', 'display': 'some display' , 'system': 'http://snomed.info/sct' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('')
        expect(cc.display).toBe('some display')
      } else { // Has no valueset
        ext.codeableConcept = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('somecode')
        expect(cc.display).toBe('some display')
      }
    })
  })
})
