// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectProblemSignificance1 = require('../../../src/Extensions/ExtensionCareConnectProblemSignificance1.js')

describe('Care Connect Extension ExtensionCareConnectProblemSignificance1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectProblemSignificance1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectProblemSignificance1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ProblemSignificance-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Code', function () {
      let ext = new ExtensionCareConnectProblemSignificance1()
      ext.code = 'foo'
      let cd = ext.code
      expect(cd).toBe('foo')
    })
  })
})
