// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectDeathNotificationStatus1 = require('../../../src/Extensions/ExtensionCareConnectDeathNotificationStatus1.js')

describe('Care Connect Extension ExtensionCareConnectDeathNotificationStatus1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectDeathNotificationStatus1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectDeathNotificationStatus1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-DeathNotificationStatus-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set deathNotificationStatus', function () {
      let ext = new ExtensionCareConnectDeathNotificationStatus1()
      // codeableconcept
      ext.deathNotificationStatus = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
      let value = ext.deathNotificationStatus
      expect(value.code).toBe('somecode')
      expect(value.display).toBe('some display')
    })
    it('Get/Set systemEffectiveDate', function () {
      let ext = new ExtensionCareConnectDeathNotificationStatus1()
      // datetime
      ext.systemEffectiveDate = 'foobar'
    })
  })
})
