// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectAdmissionMethod1 = require('../../../src/Extensions/ExtensionCareConnectAdmissionMethod1.js')

describe('Care Connect Extension ExtensionCareConnectAdmissionMethod1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectAdmissionMethod1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectAdmissionMethod1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-AdmissionMethod-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set Codeableconcept', function () {
      let ext = new ExtensionCareConnectAdmissionMethod1()
      if (!ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = '11'
        let cc = ext.codeableConcept
        expect(cc.code).toBe('11')
        expect(cc.display).toBe('Waiting list')
      } else if (ext.needsSnomed() && ext.hasValueSet()) {
        ext.codeableConcept = { 'code': '11', 'display': 'some display' , 'system': 'http://snomed.info/sct' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('11')
        expect(cc.display).toBe('some display')
      } else { // Has no valueset
        ext.codeableConcept = { 'code': 'somecode', 'display': 'some display' , 'system': 'somesystem' }
        let cc = ext.codeableConcept
        expect(cc.code).toBe('somecode')
        expect(cc.display).toBe('some display')
      }
    })
  })
})
