// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectRelatedProblemHeader1 = require('../../../src/Extensions/ExtensionCareConnectRelatedProblemHeader1.js')

describe('Care Connect Extension ExtensionCareConnectRelatedProblemHeader1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectRelatedProblemHeader1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectRelatedProblemHeader1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-RelatedProblemHeader-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set type', function () {
      let ext = new ExtensionCareConnectRelatedProblemHeader1()
      // code
      ext.type = 'foobar'
    })
    it('Get/Set target', function () {
      let ext = new ExtensionCareConnectRelatedProblemHeader1()
      // reference
      ext.target = { 'display': 'some display', 'reference': 'someref' }
      let value = ext.target
      expect(value.reference).toBe('someref')
      expect(value.display).toBe('some display')
    })
  })
})
