// This code was autogenerated from BuildExtensions.py

const ExtensionCareConnectAppointmentCancellationReason1 = require('../../../src/Extensions/ExtensionCareConnectAppointmentCancellationReason1.js')

describe('Care Connect Extension ExtensionCareConnectAppointmentCancellationReason1', function () {
  describe('Object constructor', function () {
    it('Can create object', function () {
      let ext = new ExtensionCareConnectAppointmentCancellationReason1()
      expect(ext).toBeInstanceOf(ExtensionCareConnectAppointmentCancellationReason1)
      expect(ext.url).toBe('https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-AppointmentCancellationReason-1')
    })
  })
  describe('Object getters and setters', function () {
    it('Get/Set String', function () {
      let ext = new ExtensionCareConnectAppointmentCancellationReason1()
      ext.string = 'some string'
      let s = ext.string
      expect(s).toBe('some string')
    })
  })
})
