// This file was auto generated from the url
// https://fhir.hl7.org.uk/STU3/ValueSet/CareConnect-AdministrativeGender-1
const administrativegenderCodeSystem = require('../../src/CodeSystems/administrativegender.js')
const CareConnectBaseValueSet = require('../BaseClasses/CareConnect-BaseValueSet')
let vsJsn = { 'status': 'draft', 'resourceType': 'ValueSet', 'id': 'CareConnect-AdministrativeGender-1', 'name': 'Administrative Gender', 'url': 'https://fhir.hl7.org.uk/STU3/ValueSet/CareConnect-AdministrativeGender-1', 'copyright': 'Copyright © HL7.org 2011+', 'publisher': 'HL7 (FHIR Project)', 'identifier': [{ 'value': 'urn:oid:2.16.840.1.113883.4.642.3.1', 'system': 'urn:ietf:rfc:3986' }], 'description': 'The gender of a person used for administrative purposes.', 'extension': [{ 'url': 'http://hl7.org/fhir/StructureDefinition/valueset-map', 'valueReference': { 'reference': 'https://fhir.hl7.org.uk/STU3/ConceptMap/AdministrativeGender-1' } }, { 'valueUri': 'http://hl7.org/fhir/ValueSet/administrative-gender', 'url': 'http://hl7.org/fhir/StructureDefinition/valueset-sourceReference' }, { 'valueCode': 'pc', 'url': 'http://hl7.org/fhir/StructureDefinition/structuredefinition-wg' }, { 'url': 'http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm', 'valueInteger': 5 }, { 'valueString': 'Informative', 'url': 'http://hl7.org/fhir/StructureDefinition/structuredefinition-ballot-status' }], 'version': '3.0.1', 'compose': { 'include': [{ 'concept': [{ 'display': 'Male', 'code': 'male' }, { 'display': 'Female', 'code': 'female' }, { 'display': 'Other', 'code': 'other' }, { 'display': 'Unknown', 'code': 'unknown' }], 'system': 'http://hl7.org/fhir/administrative-gender' }] }, 'date': '2017-04-19T07:46:00+10:00', 'contact': [{ 'telecom': [{ 'value': 'http://hl7.org/fhir', 'system': 'url' }, { 'value': 'fhir@lists.hl7.org', 'system': 'email' }] }] }
const CareConnectAdministrativeGender1 = new CareConnectBaseValueSet(vsJsn)
CareConnectAdministrativeGender1.code_systems = []
CareConnectAdministrativeGender1.needs_snomed = false
CareConnectAdministrativeGender1.code_systems.push(administrativegenderCodeSystem)
module.exports = CareConnectAdministrativeGender1
