// This file was auto generated from the url
// https://fhir.hl7.org.uk/STU3/ValueSet/CareConnect-ReactionEventSeverity-1
const reactioneventseverityCodeSystem = require('../../src/CodeSystems/reactioneventseverity.js')
const CareConnectBaseValueSet = require('../BaseClasses/CareConnect-BaseValueSet')
let vsJsn = { 'status': 'draft', 'resourceType': 'ValueSet', 'id': 'CareConnect-ReactionEventSeverity-1', 'name': 'AllergyIntoleranceSeverity', 'url': 'https://fhir.hl7.org.uk/STU3/ValueSet/CareConnect-ReactionEventSeverity-1', 'copyright': 'Copyright © HL7.org 2011+', 'publisher': 'HL7 (FHIR Project)', 'identifier': [{ 'value': 'urn:oid:2.16.840.1.113883.4.642.3.125', 'system': 'urn:ietf:rfc:3986' }], 'description': 'Clinical assessment of the severity of a reaction event as a whole, potentially considering multiple different manifestations.', 'extension': [{ 'url': 'http://hl7.org/fhir/StructureDefinition/valueset-map', 'valueReference': { 'reference': 'https://fhir.hl7.org.uk/STU3/ConceptMap/CareConnect-AllergySeverity-1' } }, { 'valueUri': 'http://hl7.org/fhir/valueset-reaction-event-severity', 'url': 'http://hl7.org/fhir/StructureDefinition/valueset-sourceReference' }, { 'valueCode': 'pc', 'url': 'http://hl7.org/fhir/StructureDefinition/structuredefinition-wg' }, { 'url': 'http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm', 'valueInteger': 3 }, { 'valueString': 'Informative', 'url': 'http://hl7.org/fhir/StructureDefinition/structuredefinition-ballot-status' }], 'version': '3.0.1', 'compose': { 'include': [{ 'concept': [{ 'display': 'Mild', 'code': 'mild' }, { 'display': 'Moderate', 'code': 'moderate' }, { 'display': 'Severe', 'code': 'severe' }], 'system': 'http://hl7.org/fhir/reaction-event-severity' }] }, 'date': '2017-04-19T07:44:47+10:00', 'contact': [{ 'telecom': [{ 'value': 'http://hl7.org/fhir', 'system': 'url' }] }] }
const CareConnectReactionEventSeverity1 = new CareConnectBaseValueSet(vsJsn)
CareConnectReactionEventSeverity1.code_systems = []
CareConnectReactionEventSeverity1.needs_snomed = false
CareConnectReactionEventSeverity1.code_systems.push(reactioneventseverityCodeSystem)
module.exports = CareConnectReactionEventSeverity1
