// This code was autogenerated from BuildExtensions.py

const FHIRServer = require('../..')
const CareConnectBaseExtension = require('../BaseClasses/CareConnect-BaseExtension')
let ValueSet = require('')

class ExtensionCareConnectDeliveryChannel1 extends CareConnectBaseExtension {
  constructor (opt) {
    super(opt)
    opt && delete opt.resourceType
    Object.assign(this, opt)
    this.valueSet = ValueSet
    this.url = 'https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-DeliveryChannel-1'
  }
  set code (newValue) {
    this.valueCode = newValue
  }

  get code () {
    return this.valueCode
  }
}

module.exports = ExtensionCareConnectDeliveryChannel1
