// This code was autogenerated from BuildExtensions.py

const FHIRServer = require('../..')
const CareConnectBaseExtension = require('../BaseClasses/CareConnect-BaseExtension')

class ExtensionCareConnectMedicationStatusReason1 extends CareConnectBaseExtension {
  constructor (opt) {
    super(opt)
    opt && delete opt.resourceType
    Object.assign(this, opt)
    this.url = 'https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-MedicationStatusReason-1'
  }
  set statusReason (value) {
    // let max = 1
    // let min = 1
    let ext = new CareConnectBaseExtension()
    ext.url = 'statusReason'
    ext.valueCodeableConcept = value
    // TODO Check max/clear existing slice
    if (!this.__data.extension) {
      this.__data.extension = []
    }
    this.__data.extension.push(ext)
  }

  get statusReason () {
    let ext = this.__data.extension.find(e => e.url === 'statusReason')
    return ext && ext.valueCodeableConcept
  }
  set statusChangeDate (value) {
    // let max = 1
    // let min = None
    let ext = new CareConnectBaseExtension()
    ext.url = 'statusChangeDate'
    ext.valueDateTime = value
    // TODO Check max/clear existing slice
    if (!this.__data.extension) {
      this.__data.extension = []
    }
    this.__data.extension.push(ext)
  }

  get statusChangeDate () {
    let ext = this.__data.extension.find(e => e.url === 'statusChangeDate')
    return ext && ext.valueDateTime
  }
}

module.exports = ExtensionCareConnectMedicationStatusReason1
