// This code was autogenerated from BuildExtensions.py

const FHIRServer = require('../..')
const CareConnectBaseExtension = require('../BaseClasses/CareConnect-BaseExtension')

class ExtensionCareConnectEncounterTransport1 extends CareConnectBaseExtension {
  constructor (opt) {
    super(opt)
    opt && delete opt.resourceType
    Object.assign(this, opt)
    this.url = 'https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-EncounterTransport-1'
  }
  set transportType (value) {
    // let max = 1
    // let min = 1
    let ext = new CareConnectBaseExtension()
    ext.url = 'transportType'
    ext.valueCodeableConcept = value
    // TODO Check max/clear existing slice
    if (!this.__data.extension) {
      this.__data.extension = []
    }
    this.__data.extension.push(ext)
  }

  get transportType () {
    let ext = this.__data.extension.find(e => e.url === 'transportType')
    return ext && ext.valueCodeableConcept
  }
  set transportPeriod (value) {
    // let max = 1
    // let min = None
    let ext = new CareConnectBaseExtension()
    ext.url = 'transportPeriod'
    ext.valuePeriod = value
    // TODO Check max/clear existing slice
    if (!this.__data.extension) {
      this.__data.extension = []
    }
    this.__data.extension.push(ext)
  }

  get transportPeriod () {
    let ext = this.__data.extension.find(e => e.url === 'transportPeriod')
    return ext && ext.valuePeriod
  }
  set reasonForTransport (value) {
    // let max = 1
    // let min = None
    let ext = new CareConnectBaseExtension()
    ext.url = 'reasonForTransport'
    ext.valueString = value
    // TODO Check max/clear existing slice
    if (!this.__data.extension) {
      this.__data.extension = []
    }
    this.__data.extension.push(ext)
  }

  get reasonForTransport () {
    let ext = this.__data.extension.find(e => e.url === 'reasonForTransport')
    return ext && ext.valueString
  }
}

module.exports = ExtensionCareConnectEncounterTransport1
