// This code was autogenerated from BuildExtensions.py

const FHIRServer = require('../..')
const CareConnectBaseExtension = require('../BaseClasses/CareConnect-BaseExtension')

class ExtensionCareConnectRecorder1 extends CareConnectBaseExtension {
  constructor (opt) {
    super(opt)
    opt && delete opt.resourceType
    Object.assign(this, opt)
    this.url = 'https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-Recorder-1'
    this.targetReferences = []
  }
  set reference (newValue) {
    this.valueReference = newValue
  }

  get reference () {
    return this.valueReference
  }
}

module.exports = ExtensionCareConnectRecorder1
