// This code was autogenerated from BuildExtensions.py

const FHIRServer = require('../..')
const CareConnectBaseExtension = require('../BaseClasses/CareConnect-BaseExtension')

class ExtensionCareConnectValueApproximation1 extends CareConnectBaseExtension {
  constructor (opt) {
    super(opt)
    opt && delete opt.resourceType
    Object.assign(this, opt)
    this.url = 'https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ValueApproximation-1'
  }
  set boolean (bool) {
    this.valueBoolean = bool
  }

  get boolean () {
    return this.valueBoolean
  }
}

module.exports = ExtensionCareConnectValueApproximation1
