// This code was autogenerated from BuildExtensions.py

const FHIRServer = require('../..')
const CareConnectBaseExtension = require('../BaseClasses/CareConnect-BaseExtension')

class ExtensionCareConnectAllergyIntoleranceEnd1 extends CareConnectBaseExtension {
  constructor (opt) {
    super(opt)
    opt && delete opt.resourceType
    Object.assign(this, opt)
    this.url = 'https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-AllergyIntoleranceEnd-1'
  }
  set endDate (value) {
    // let max = 1
    // let min = None
    let ext = new CareConnectBaseExtension()
    ext.url = 'endDate'
    ext.valueDateTime = value
    // TODO Check max/clear existing slice
    if (!this.__data.extension) {
      this.__data.extension = []
    }
    this.__data.extension.push(ext)
  }

  get endDate () {
    let ext = this.__data.extension.find(e => e.url === 'endDate')
    return ext && ext.valueDateTime
  }
  set reasonEnded (value) {
    // let max = 1
    // let min = None
    let ext = new CareConnectBaseExtension()
    ext.url = 'reasonEnded'
    ext.valueString = value
    // TODO Check max/clear existing slice
    if (!this.__data.extension) {
      this.__data.extension = []
    }
    this.__data.extension.push(ext)
  }

  get reasonEnded () {
    let ext = this.__data.extension.find(e => e.url === 'reasonEnded')
    return ext && ext.valueString
  }
}

module.exports = ExtensionCareConnectAllergyIntoleranceEnd1
