// This code was autogenerated from BuildExtensions.py

const FHIRServer = require('../..')
const CareConnectBaseExtension = require('../BaseClasses/CareConnect-BaseExtension')

class ExtensionCareConnectMedicationRepeatInformation1 extends CareConnectBaseExtension {
  constructor (opt) {
    super(opt)
    opt && delete opt.resourceType
    Object.assign(this, opt)
    this.url = 'https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-MedicationRepeatInformation-1'
  }
  set numberOfRepeatPrescriptionsAllowed (value) {
    // let max = 1
    // let min = None
    let ext = new CareConnectBaseExtension()
    ext.url = 'numberOfRepeatPrescriptionsAllowed'
    ext.valueUnsignedInt = value
    // TODO Check max/clear existing slice
    if (!this.__data.extension) {
      this.__data.extension = []
    }
    this.__data.extension.push(ext)
  }

  get numberOfRepeatPrescriptionsAllowed () {
    let ext = this.__data.extension.find(e => e.url === 'numberOfRepeatPrescriptionsAllowed')
    return ext && ext.valueUnsignedInt
  }
  set numberOfRepeatPrescriptionsIssued (value) {
    // let max = 1
    // let min = None
    let ext = new CareConnectBaseExtension()
    ext.url = 'numberOfRepeatPrescriptionsIssued'
    ext.valueUnsignedInt = value
    // TODO Check max/clear existing slice
    if (!this.__data.extension) {
      this.__data.extension = []
    }
    this.__data.extension.push(ext)
  }

  get numberOfRepeatPrescriptionsIssued () {
    let ext = this.__data.extension.find(e => e.url === 'numberOfRepeatPrescriptionsIssued')
    return ext && ext.valueUnsignedInt
  }
  set authorisationExpiryDate (value) {
    // let max = 1
    // let min = None
    let ext = new CareConnectBaseExtension()
    ext.url = 'authorisationExpiryDate'
    ext.valueDateTime = value
    // TODO Check max/clear existing slice
    if (!this.__data.extension) {
      this.__data.extension = []
    }
    this.__data.extension.push(ext)
  }

  get authorisationExpiryDate () {
    let ext = this.__data.extension.find(e => e.url === 'authorisationExpiryDate')
    return ext && ext.valueDateTime
  }
}

module.exports = ExtensionCareConnectMedicationRepeatInformation1
